apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

    name: kb-ing
  spec:
    rules:
    - host: kb-navarrow.kube.um.edu.ar
      http:
        paths:
        - backend:
            serviceName: kb-prod
            servicePort: 80
          path: /
